### ISSUE TITLE
GSC Sabrina's Mr Mime does not appear

### ISSUE THREAD

**Issue by SkullheadMcShay** [KinglerChamp/VanillaNuzlockeCalc#14]
When looking for Sabrina's Mr Mime in GSC, it doesn't appear.
![image](https://github.com/user-attachments/assets/0a5416e1-e9bf-41a8-ad89-4c602d5f1d92)

You can still select it from Sabrina's team if you pick one of her other pokémon, but the sprite is missing and clicking it only changes the display name on the search bar, not the stats or moves.
![image](https://github.com/user-attachments/assets/8d816acd-2821-4bb4-8934-14c421205a05)

![image](https://github.com/user-attachments/assets/acf1ba27-1de7-444d-8ff0-7dcc02b8c93f)

**Comment by KinglerChamp** [comment]
Found the issue. this will be fixed in the upcoming patch thank you
