### ISSUE TITLE
Bug with Natures in Gen 4 (Platinum)

### ISSUE THREAD

**Issue by violll** [KinglerChamp/VanillaNuzlockeCalc#19]
A fair number of trainers' pokemon are showing up in the calc with Hardy natures when that isn't the nature they have.

I looked at Plat.js and it looks like some entries in the dict have the nature and ability keys and values swapped. 

This is line 157 of Plat.js:
`"Cherrim":{"Leader Gardenia | Plat ":{"index":"420000000103","level":20,"ability":"Lax","item":"None","nature":"Flower Gift","ivs":{"hp":6,"at":6,"df":6,"sa":6,"sd":6,"sp":6},"moves":["Grass Knot","Leech Seed","Magical Leaf","Safeguard",]},`

Shouldn't it be `"nature": "Lax", "ability": "Flower Gift"`?

**Comment by KinglerChamp** [comment]
Yes you are correct. That's an issue in my excel sheet that I pull from that I thought I fixed but apparently missed some. I'll fix soon. Thank you
