### ISSUE TITLE
Wrong levels for BW2 Challenge Mode (Hardmode)

### ISSUE THREAD

**Issue by maxshinnerl** [KinglerChamp/VanillaNuzlockeCalc#22]
Gym leaders/E4/champion have the normal Black 2/White 2 levels instead of their increased levels in challenge mode.  May extend to more trainers if applicable, those are just the ones I checked.

**Comment by KinglerChamp** [comment]
This is a intentional change. As challenge and easy mode, even though the game displays higher/lower levels, the stats aren't actually different from normal mode. This is a glitch with the code for the games.

**Comment by maxshinnerl** [comment]
That's wild, my bad and thanks for the info
